variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=INFO -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s .gitlab-ci-mvn-settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:3.6.3-openjdk-11-slim
  stage: build
  script: 
    - "mvn $MAVEN_CLI_OPTS clean package -DskipTests"

maven-test:
  image: maven:3.6.3-openjdk-11-slim
  stage: test
  script: 
    - "mvn $MAVEN_CLI_OPTS test"

maven-deploy-private-gitlab-package-registry:
  image: maven:3.6.3-openjdk-11-slim
  stage: deploy
  script:
    - "mvn $MAVEN_CLI_OPTS deploy -P private-gitlab-package-registry-deploy"
  only:
    refs:
      - main

maven-deploy-private-nexus-repository:
  image: maven:3.6.3-openjdk-11-slim
  stage: deploy
  script:
    - "mvn $MAVEN_CLI_OPTS deploy -P private-nexus-repository-deploy"
  only:
    refs:
      - main
